repos:
- repo: local
  hooks:
  - id: isort
    name: isort
    stages: [commit]
    language: system
    entry: poetry run isort --profile black --check-only
    types: [python]

  - id: black
    name: black
    stages: [commit]
    language: system
    entry: poetry run black --check
    types: [python]